### ISSUE TITLE
opencpu is not working after upgrading R from 4.1 to 4.2

### ISSUE THREAD

**Issue by OdilKurbanov** [opencpu/opencpu#402]
In https://MY_SERVER/ocpu/test/ while sending HTTP request
Im reseiving message "R package library for user [USERNAME] not found."

Before upgrade everything was working without any problem.

**Comment by jeroen** [comment]
What URL to you invoke? Or do you see this error for the test page itself?

**Comment by cscrewsandcaptains** [comment]
I have the same problem after updating 4.1.2 -> 4.2 and opencpu 2.2.7 -> 2.2.8
I found out that .libPath is without ‘/usr/local/lib/R/site-library’:
[1] "/usr/lib/R/library"                  "/usr/local/lib/opencpu/site-library"
[3] "/usr/lib/R/site-library"             "/usr/lib/opencpu/library"           
by calling
http://localhost/ocpu/library/base/R/.libPaths
What can I do?

**Comment by OdilKurbanov** [comment]
> What URL to you invoke? Or do you see this error for the test page itself?

I see this error in test page, also none of my HTTP requests are working. ufter upgrade. I also upgraded 4.1.2 -> 4.2 and opencpu 2.2.7 -> 2.2.8

**Comment by jeroen** [comment]
Hmm weird sorry about that. I'll look into it. The upgrade went fine on https://cloud.opencpu.org

**Comment by OdilKurbanov** [comment]
Update. I removed opencpu, rstudio then installed them again. The problem exists.

**Comment by jeroen** [comment]
OK I found the source of the problem. The `r-base` debian package has changed the location in which R_LIBS_SITE and R_LIBS_USER get set, and apparently the new location is not recognized by rApache.

Dirk says: 

> What we had went back to a discussion in a pub in Vienna where Kurt and Fritz convinced me to support the 'three elements in .libPaths'.   Now, when I started with the R 4.2.0 pre-release I noticed after the first or second that /usr/local/lib/R/site-library was no longer effective. Reason: R Core pre-set R_LIBS and R_SITE in Renviron meaning my use depending on _empty values_ no longer worked.  So I accomodated and moved to Renviron.site

**Comment by jeroen** [comment]
I have pushed some fixes. Can you try again?

**Comment by OdilKurbanov** [comment]
The problem still there:
![изображение](https://user-images.githubusercontent.com/48148916/168738038-62a55f81-e0e3-4fb0-8c83-9bbd5c1c404a.png)

![изображение](https://user-images.githubusercontent.com/48148916/168737955-5ee0b68f-ec6e-4bb0-82c6-34deb60b23d5.png)

![изображение](https://user-images.githubusercontent.com/48148916/168738785-e92f0bec-301b-480d-b096-872ce3867bf2.png)

**Comment by cscrewsandcaptains** [comment]
2.2.8-focal2 solves my problem, thank you for the quick response!

**Comment by jeroen** [comment]
@OdilKurbanov are you sure that there are packages installed in the opencpu home dir? How did you install those packages?

**Comment by OdilKurbanov** [comment]
Actually I'm using my own user:
![изображение](https://user-images.githubusercontent.com/48148916/168761864-0e93a99a-f465-47c1-8c7d-7e7866fa85c1.png)


I'm installing packages from RStudio using my user:
![изображение](https://user-images.githubusercontent.com/48148916/168761662-c95b65a5-71cb-481a-b3da-3b8762cc1cfe.png)

**Comment by jeroen** [comment]
@OdilKurbanov it could be that you have to reinstall some packages, because the default home library is versioned:

 - /home/jeroen/R/x86_64-pc-linux-gnu-library/4.1
 - /home/jeroen/R/x86_64-pc-linux-gnu-library/4.2

In Rstudio can you look at your `.libPaths()` ? And see if the packages are still in there?

**Comment by OdilKurbanov** [comment]
Yes there are packages installed in /home/analyst/R/x86_64-pc-linux-gnu-library/4.2 
![изображение](https://user-images.githubusercontent.com/48148916/168767428-ae8737b0-5763-4d78-a1df-20f5bc0887ae.png)

(of course there are more packages under /home/analyst/R/x86_64-pc-linux-gnu-library/4.1)

**Comment by OdilKurbanov** [comment]
@jeroen 
> .libPaths()
[1] "/home/analyst/R/x86_64-pc-linux-gnu-library/4.2" "/usr/local/lib/R/site-library"                  
[3] "/usr/lib/R/site-library"                         "/usr/lib/R/library"

**Comment by OdilKurbanov** [comment]
@jeroen , I tried to install packages as root:
```
sudo -i
R
install.packages("httr")
```
However, I could not see that installed "httr" package in the `/ocpu/library`:
![изображение](https://user-images.githubusercontent.com/48148916/168804880-368e99d2-0096-4c93-af9a-2500e1cac335.png)

**Comment by OdilKurbanov** [comment]
> @jeroen , I tried to install packages as root:
> 
> ```
> sudo -i
> R
> install.packages("httr")
> ```
> 
> However, I could not see that installed "httr" package in the `/ocpu/library`: ![изображение](https://user-images.githubusercontent.com/48148916/168804880-368e99d2-0096-4c93-af9a-2500e1cac335.png)

Sorry, installing as /ocpu/library is working. above issue was related with ownership

**Comment by jeroen** [comment]
Yeah I think I found the issue, give me an hour to build a new release.

**Comment by OdilKurbanov** [comment]
The last version fixed the problem. Thank you very much for your kind help!

**Comment by OdilKurbanov** [comment]
Thank you for a great support!  Closing this issue.

**Comment by jeroen** [comment]
OK thanks for confirming.

To wrap up, the root cause was the change in R-4.2 (see [NEWS](https://cran.r-project.org/doc/manuals/r-release/NEWS.html)):

```
Environment variables R_LIBS_USER and R_LIBS_SITE are both now set to the R system default if unset or empty, and can be set to NULL to indicate an empty list of user or site library directories.
```

As a result, the ubuntu-specific locations of the global and user site library were no longer round.
